name: Git Push CI Pipeline

on:
  # Triggers the workflow on pushing a commit
  push:
    branches: [ mainline ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    # Sets up python3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
    - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install flake8 pytest isort
    - name: Run isort
      run: |
        isort  --recursive src/
    - name: Run linting with flake8
      run: |
        flake8 src test
    - name: Run Unit tests with pytest
      run: |
        pytest test/
